<span style="font-family: Calibri; font-size: 14px;"> 
<strong>
Python 3.12.2
</strong>
</span>

In [3]:
import pandas as pd
import pyodbc

from sqlalchemy import create_engine
from sqlalchemy import text

<span style="font-family: Calibri; font-size: 14px;"> 
Importando os arquivos CSV em pandas dataframas
</span>

In [2]:
pnad_covid_052020 = pd.read_csv("PNAD_COVID_052020.csv", sep=",")
pnad_covid_062020 = pd.read_csv("PNAD_COVID_062020.csv", sep=",")
pnad_covid_072020 = pd.read_csv("PNAD_COVID_072020.csv", sep=",")
pnad_covid_082020 = pd.read_csv("PNAD_COVID_082020.csv", sep=",")
pnad_covid_092020 = pd.read_csv("PNAD_COVID_092020.csv", sep=",")
pnad_covid_102020 = pd.read_csv("PNAD_COVID_102020.csv", sep=",")
pnad_covid_112020 = pd.read_csv("PNAD_COVID_112020.csv", sep=",")

<span style="font-family: Calibri; font-size: 14px;"> 
Testando como ficou estrutura dos dados em um dos dataframes criados
</span>

In [3]:
pnad_covid_052020

,Ano,UF,CAPITAL,RM_RIDE,V1008,V1012,V1013,V1016,Estrato,UPA,...,D0053,D0061,D0063,D0071,D0073,F001,F0021,F0022,F0061,F006
0,2020,11,11.0,NaN,1,4,5,1,1110011,110015970,...,1200.0,2,NaN,2,NaN,1,NaN,NaN,1,2.0
1,2020,11,11.0,NaN,1,4,5,1,1110011,110015970,...,1200.0,2,NaN,2,NaN,1,NaN,NaN,1,2.0
2,2020,11,11.0,NaN,1,4,5,1,1110011,110015970,...,1200.0,2,NaN,2,NaN,1,NaN,NaN,1,2.0
3,2020,11,11.0,NaN,1,4,5,1,1110011,110015970,...,1200.0,2,NaN,2,NaN,1,NaN,NaN,1,2.0
4,2020,11,11.0,NaN,3,2,5,1,1110011,110015970,...,600.0,2,NaN,2,NaN,1,NaN,NaN,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349301,2020,53,53.0,NaN,6,3,5,1,5310220,530009738,...,600.0,2,NaN,2,NaN,1,NaN,NaN,1,3.0
349302,2020,53,53.0,NaN,6,3,5,1,5310220,530009738,...,600.0,2,NaN,2,NaN,1,NaN,NaN,1,3.0
349303,2020,53,53.0,NaN,6,3,5,1,5310220,530009738,...,600.0,2,NaN,2,NaN,1,NaN,NaN,1,3.0
349304,2020,53,53.0,NaN,10,2,5,1,5310220,530009738,...,NaN,2,NaN,2,NaN,5,NaN,NaN,1,2.0
349305,2020,53,53.0,NaN,10,2,5,1,5310220,530009738,...,NaN,2,NaN,2,NaN,5,NaN,NaN,1,2.0

<span style="font-family: Calibri; font-size: 14px;"> 
Quantidade de linhas e colunas em cada dataframe
</span>

In [ ]:
print(pnad_covid_052020.shape)
print(pnad_covid_062020.shape)
print(pnad_covid_072020.shape)
print(pnad_covid_082020.shape)
print(pnad_covid_092020.shape)
print(pnad_covid_102020.shape)
print(pnad_covid_112020.shape)

(349306, 114)
(381270, 114)
(384166, 145)
(386520, 145)
(387298, 145)
(380461, 145)
(381438, 148)

<span style="font-family: Calibri; font-size: 14px;"> 
Criando um banco de dados em SQL Server
</span>

In [ ]:
conn = pyodbc.connect(
    "DRIVER={SQL Server};SERVER=localhost\\SQLEXPRESS;DATABASE=master;Trusted_Connection=yes"
)
conn.autocommit = True 

cursor = conn.cursor()

cursor.execute("CREATE DATABASE pnad_covid_db")
print("Banco criado!")

Banco criado!

<span style="font-family: Calibri; font-size: 14px;"> 
Conexão com novo banco de dados
</span>

In [4]:
engine = create_engine(
    "mssql+pyodbc://localhost\\SQLEXPRESS/pnad_covid_db?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes", fast_executemany=True
)

<span style="font-family: Calibri; font-size: 14px;"> 
Carregando os dados de cada dataframe e inserindo-os em tabelas no novo banco de dados
</span>

In [23]:
pnad_covid_052020.to_sql("pnad_covid_052020", engine, index=False, if_exists="replace", chunksize=5000) 
print("Tabela pnad_covid_052020 criada!")

pnad_covid_062020.to_sql("pnad_covid_062020", engine, index=False, if_exists="replace", chunksize=5000)
print("Tabela pnad_covid_062020 criada!")

pnad_covid_072020.to_sql("pnad_covid_072020", engine, index=False, if_exists="replace", chunksize=5000)
print("Tabela pnad_covid_072020 criada!")

pnad_covid_082020.to_sql("pnad_covid_082020", engine, index=False, if_exists="replace", chunksize=5000)
print("Tabela pnad_covid_082020 criada!")

pnad_covid_092020.to_sql("pnad_covid_092020", engine, index=False, if_exists="replace", chunksize=5000)
print("Tabela pnad_covid_092020 criada!")

pnad_covid_102020.to_sql("pnad_covid_102020", engine, index=False, if_exists="replace", chunksize=5000)
print("Tabela pnad_covid_102020 criada!")

pnad_covid_112020.to_sql("pnad_covid_112020", engine, index=False, if_exists="replace", chunksize=5000)
print("Tabela pnad_covid_112020 criada!")

Tabela pnad_covid_052020 criada!
Tabela pnad_covid_062020 criada!
Tabela pnad_covid_072020 criada!
Tabela pnad_covid_082020 criada!
Tabela pnad_covid_092020 criada!
Tabela pnad_covid_102020 criada!
Tabela pnad_covid_112020 criada!

<span style="font-family: Calibri; font-size: 14px;"> 
Testando query com uma das novas tabelas
</span>

In [25]:
query = "SELECT TOP 10 * FROM pnad_covid_112020"
df = pd.read_sql(query, engine)
df

,Ano,UF,CAPITAL,RM_RIDE,V1008,V1012,V1013,V1016,Estrato,UPA,...,F001,F0021,F0022,F002A1,F002A2,F002A3,F002A4,F002A5,F0061,F006
0,2020,11,11.0,None,1,4,11,7,1110011,110015970,...,1,None,None,1,1,1,2,1,1,1.0
1,2020,11,11.0,None,1,4,11,7,1110011,110015970,...,1,None,None,1,1,1,2,1,1,1.0
2,2020,11,11.0,None,1,4,11,7,1110011,110015970,...,1,None,None,1,1,1,2,1,1,1.0
3,2020,11,11.0,None,1,4,11,7,1110011,110015970,...,1,None,None,1,1,1,2,1,1,1.0
4,2020,11,11.0,None,2,1,11,7,1110011,110015970,...,1,None,None,1,1,1,2,1,1,1.0
5,2020,11,11.0,None,3,2,11,7,1110011,110015970,...,1,None,None,1,1,1,2,1,1,1.0
6,2020,11,11.0,None,4,4,11,7,1110011,110015970,...,1,None,None,1,1,1,2,1,1,1.0
7,2020,11,11.0,None,4,4,11,7,1110011,110015970,...,1,None,None,1,1,1,2,1,1,1.0
8,2020,11,11.0,None,4,4,11,7,1110011,110015970,...,1,None,None,1,1,1,2,1,1,1.0
9,2020,11,11.0,None,4,4,11,7,1110011,110015970,...,1,None,None,1,1,1,2,1,1,1.0

Por favor, continue no arquivo 02_pnad_covid.sql